Character.destroy_all

# character = Character.create!(
#   character: {
#     bio: {
#       name: 'character',
#       pictures: [],
#       tier: ''
#     },
#     moves: [],
#     supers: [
#     ],
#     assists: [
#
#     ],
#
#     combos: {
#
#     },
#   }
# )



android16 = Character.create!(
  character:{

  bio: {
    name: 'Android 16',
    pictures: [],
    tier: 'B'
  },
  moves: [
  {
    "MOVE": "5L",
    "FIRST ACTIVE": "7f",
    "ACTIVE": "3f",
    "RECOVERY": "17f",
    "ADVANTAGE": "-6f",
    "GUARD": "All",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LL",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "4f",
    "RECOVERY": "22f",
    "ADVANTAGE": "-10f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LLL",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "1f",
    "RECOVERY": "19f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1000,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": "SMASH"
  },
  {
    "MOVE": "2L",
    "FIRST ACTIVE": "8f",
    "ACTIVE": "3f",
    "RECOVERY": "13f",
    "ADVANTAGE": "-4f",
    "GUARD": "LOW",
    "DAMAGE": 500,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5M",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "3f",
    "RECOVERY": "19f",
    "ADVANTAGE": "-11f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "2M",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "4f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-12f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5H",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "11f",
    "RECOVERY": "21f",
    "ADVANTAGE": "-8f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "strk.armor 13f - 25f",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "2H",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "9f",
    "RECOVERY": "29f",
    "ADVANTAGE": "-22f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "4f anti-air, strkarmor 15f - 23f / INITIAL SMASH",
    "EXTENSION": ""
  },
  {
    "MOVE": "5S ; 5S",
    "FIRST ACTIVE": "15f ; 35",
    "ACTIVE": "- ; -",
    "RECOVERY": "41f ; 41f from first active",
    "ADVANTAGE": "Point blank -10f* ; -10f*",
    "GUARD": "All",
    "DAMAGE": "600 ; 600",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "Chain up to 2",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.L",
    "FIRST ACTIVE": "8f",
    "ACTIVE": "10f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.M",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "6f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.H",
    "FIRST ACTIVE": "17f",
    "ACTIVE": "8f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "strk.armor 15f - 24f",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.2H",
    "FIRST ACTIVE": "21f",
    "ACTIVE": "until lands",
    "RECOVERY": "20f from landing",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 850,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.S",
    "FIRST ACTIVE": "18f ; 33f",
    "ACTIVE": "-",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "600 ; 600",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "MOVE",
    "FIRST ACTIVE": "FIRST ACTIVE",
    "ACTIVE": "ACTIVE",
    "RECOVERY": "RECOVERY",
    "ADVANTAGE": "ADVANTAGE",
    "GUARD": "GUARD",
    "DAMAGE": "DAMAGE",
    "PRORATION init/comb": "PRORATION init/comb",
    "SPECIAL": "SPECIAL",
    "EXTENSION": "EXTENSION"
  },
  {
    "MOVE": "236L",
    "FIRST ACTIVE": "17f",
    "ACTIVE": "1f",
    "RECOVERY": "26f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1500,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": "SKD"
  },
  {
    "MOVE": "236M",
    "FIRST ACTIVE": "28f",
    "ACTIVE": "1f",
    "RECOVERY": "28f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1550,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "Ki-blast invuln 5f - 27f",
    "EXTENSION": "WALL BOUNCE ; SKD"
  },
  {
    "MOVE": "236H (1bar)",
    "FIRST ACTIVE": "26f",
    "ACTIVE": "1f",
    "RECOVERY": "28f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1550,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "Ki-blast invuln 3f - 25f",
    "EXTENSION": "WALL BOUNCE ; SKD"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236L",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "3f",
    "RECOVERY": "27f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1400,
    "PRORATION init/comb": "60% / +1",
    "SPECIAL": "",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "j.236M",
    "FIRST ACTIVE": "19f",
    "ACTIVE": "10f",
    "RECOVERY": "26f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": "1400, 200",
    "PRORATION init/comb": "70% +1 / +1 +1",
    "SPECIAL": "",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "j.236H (1bar)",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "8f",
    "RECOVERY": "26f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": "1400, 200",
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214L",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "11f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1400,
    "PRORATION init/comb": "60% / +1",
    "SPECIAL": "Anti-air 4f - 10f",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "214M",
    "FIRST ACTIVE": "19f",
    "ACTIVE": "9f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1400,
    "PRORATION init/comb": "60% / +1",
    "SPECIAL": "Anti-air 4f - 19f",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "214H (1bar)",
    "FIRST ACTIVE": "6f ; 13f",
    "ACTIVE": "2f ; 9f",
    "RECOVERY": "14f",
    "ADVANTAGE": "-1f ; -",
    "GUARD": "All ; Throw",
    "DAMAGE": "300 ; 1500",
    "PRORATION init/comb": "70% / +1 +1",
    "SPECIAL": "Anti-air 1f - 13f",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214L",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "11f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1400,
    "PRORATION init/comb": "60% / +1",
    "SPECIAL": "",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "j.214M",
    "FIRST ACTIVE": "19f",
    "ACTIVE": "9f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1400,
    "PRORATION init/comb": "60% / +1",
    "SPECIAL": "",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "j.214H (1bar)",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "9f",
    "RECOVERY": "14f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1800,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": "Counsumes Smash"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "15f",
    "RECOVERY": "21f",
    "ADVANTAGE": "-1f",
    "GUARD": "All",
    "DAMAGE": "270, 270 x3",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214S",
    "FIRST ACTIVE": "24f",
    "ACTIVE": "15f",
    "RECOVERY": "18f",
    "ADVANTAGE": "4f",
    "GUARD": "All",
    "DAMAGE": "150, 150 x7",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  }
],
  supers: [
  ],
  assists: [

  ],

  combos: {

  },



})
android17 = Character.create!(
  character: {
    bio: {
      name: 'Android 17',
      pictures: [],
      tier: 'B'
    },
    moves: [
  {
    "MOVE": "5L",
    "FIRST ACTIVE": "6f",
    "ACTIVE": "2f",
    "RECOVERY": "13f",
    "ADVANTAGE": "−3f",
    "GUARD": "All",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "5LL",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "5f",
    "RECOVERY": "16f",
    "ADVANTAGE": "−5f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "Stealth nerfed from -2f to -5f",
    "__1": ""
  },
  {
    "MOVE": "5LLL",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "4f",
    "RECOVERY": "17f",
    "ADVANTAGE": "−5f",
    "GUARD": "All",
    "DAMAGE": 1000,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "SMASH",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "2L",
    "FIRST ACTIVE": "7f",
    "ACTIVE": "3f",
    "RECOVERY": "13f",
    "ADVANTAGE": "−4f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "5M",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "4f",
    "RECOVERY": "17f",
    "ADVANTAGE": "−5f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "2M",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "4f",
    "RECOVERY": "18f",
    "ADVANTAGE": "−6f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "5H",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "4f",
    "RECOVERY": "22f",
    "ADVANTAGE": "−10f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "3H",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "6f",
    "RECOVERY": "18f",
    "ADVANTAGE": "-8f",
    "GUARD": "LOW",
    "DAMAGE": 750,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "2H",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "3f",
    "RECOVERY": "29f",
    "ADVANTAGE": "−16f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "Air invuln at 4f",
    "EXTENSION": "INITIAL SMASH",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "5S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "-",
    "ADVANTAGE": "−4f *",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1 (+1 per)",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "22S",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "3f",
    "RECOVERY": "49f",
    "ADVANTAGE": "-28f",
    "GUARD": "All",
    "DAMAGE": 800,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "Charges 22S",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "22S (Charged)",
    "FIRST ACTIVE": "17f, 34f",
    "ACTIVE": "-",
    "RECOVERY": "Total frames 63f",
    "ADVANTAGE": "point blank: 6f",
    "GUARD": "All",
    "DAMAGE": "1440 raw, 180 scaled",
    "PRORATION init/comb": "80% +1 / +1 +1",
    "SPECIAL": "Consumes charge, Causes SKD",
    "EXTENSION": "",
    "": "80% +1 / +2 +1",
    "__1": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "j.L",
    "FIRST ACTIVE": "6f",
    "ACTIVE": "3f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "j.M",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "3f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "j.H",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "4f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "j.2H",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "5f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "ALL",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "j.S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "ALL",
    "DAMAGE": "250 x2",
    "PRORATION init/comb": "(+2, +1 per volley)",
    "SPECIAL": "Scales seperately",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "j.22S",
    "FIRST ACTIVE": "16f",
    "ACTIVE": "-",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "1440 raw, 180 scaled",
    "PRORATION init/comb": "80% +1 / +2 +1",
    "SPECIAL": "Consumes charge, Causes SKD",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "MOVE",
    "FIRST ACTIVE": "FIRST ACTIVE",
    "ACTIVE": "ACTIVE",
    "RECOVERY": "RECOVERY",
    "ADVANTAGE": "ADVANTAGE",
    "GUARD": "GUARD",
    "DAMAGE": "DAMAGE",
    "PRORATION init/comb": "PRORATION init/comb",
    "SPECIAL": "SPECIAL",
    "EXTENSION": "EXTENSION",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "236L",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "4f",
    "RECOVERY": "35f",
    "ADVANTAGE": "-19f",
    "GUARD": "All",
    "DAMAGE": 900,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "Air invulnerable at 4f",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "236M",
    "FIRST ACTIVE": "25f - 31f",
    "ACTIVE": "4f",
    "RECOVERY": "35f",
    "ADVANTAGE": "-19f",
    "GUARD": "All",
    "DAMAGE": 950,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "Air invulnerable at 4f",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "236[M]",
    "FIRST ACTIVE": "Total frames 33f",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "-",
    "PRORATION init/comb": "- / -",
    "SPECIAL": "Feint",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "236H",
    "FIRST ACTIVE": "33f - 47f",
    "ACTIVE": "4f",
    "RECOVERY": "35f",
    "ADVANTAGE": "-19f",
    "GUARD": "All, CROSSUP",
    "DAMAGE": 1000,
    "PRORATION init/comb": "60% / +2",
    "SPECIAL": "Air invulnerable at 1f, Always swaps sides",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "236[H]",
    "FIRST ACTIVE": "Total frames 38f",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "-",
    "PRORATION init/comb": "- / -",
    "SPECIAL": "Air invulnerable at 1f, Feint, swaps sides",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "214L",
    "FIRST ACTIVE": "31f",
    "ACTIVE": "4f",
    "RECOVERY": "35f",
    "ADVANTAGE": "-19f",
    "GUARD": "All",
    "DAMAGE": 900,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "Air invulnerable at 23f, earliest cancel at 20f",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "214M",
    "FIRST ACTIVE": "37f - 44f",
    "ACTIVE": "4f",
    "RECOVERY": "35f",
    "ADVANTAGE": "-19f",
    "GUARD": "All",
    "DAMAGE": 950,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "Air invulnerable at 28f, earliest cancel at 23f",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "214[M]",
    "FIRST ACTIVE": "Total frames 49f",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "-",
    "PRORATION init/comb": "- / -",
    "SPECIAL": "Feint",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "214H",
    "FIRST ACTIVE": "40f - 51f",
    "ACTIVE": "4f",
    "RECOVERY": "35f",
    "ADVANTAGE": "-19f",
    "GUARD": "All, CROSSUP",
    "DAMAGE": 1000,
    "PRORATION init/comb": "60% / +2",
    "SPECIAL": "Always swaps sides, earliest cancel at 20f",
    "EXTENSION": "",
    "": "air invuln at 23f",
    "__1": ""
  },
  {
    "MOVE": "214[H]",
    "FIRST ACTIVE": "Total frames 47f",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "-",
    "PRORATION init/comb": "- / -",
    "SPECIAL": "Feint, swaps sides",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "REKKA FOLLOWUPS:",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 5L",
    "FIRST ACTIVE": "8f",
    "ACTIVE": "6f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-9f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 5M",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "6f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-9f",
    "GUARD": "All",
    "DAMAGE": 750,
    "PRORATION init/comb": "90% +1",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 4L",
    "FIRST ACTIVE": "Cancellable at 22f",
    "ACTIVE": "",
    "RECOVERY": "17f from cancel window",
    "ADVANTAGE": "-",
    "GUARD": "",
    "DAMAGE": "-",
    "PRORATION init/comb": "",
    "SPECIAL": "Feint",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 4M",
    "FIRST ACTIVE": "Cancellable at 25f",
    "ACTIVE": "",
    "RECOVERY": "17f from cancel window",
    "ADVANTAGE": "-",
    "GUARD": "",
    "DAMAGE": "-",
    "PRORATION init/comb": "",
    "SPECIAL": "Feint",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 6L",
    "FIRST ACTIVE": "25f",
    "ACTIVE": "3f",
    "RECOVERY": "25f",
    "ADVANTAGE": "-12f",
    "GUARD": "HIGH",
    "DAMAGE": 700,
    "PRORATION init/comb": "60% / +2",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "1.15-1.17 70% / +2",
    "__1": ""
  },
  {
    "MOVE": "> 6M",
    "FIRST ACTIVE": "26f",
    "ACTIVE": "4f",
    "RECOVERY": "25f",
    "ADVANTAGE": "-13f",
    "GUARD": "HIGH",
    "DAMAGE": 750,
    "PRORATION init/comb": "60% / +2",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "1.15-1.17 70% / +2",
    "__1": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 2L",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "4f",
    "RECOVERY": "26f",
    "ADVANTAGE": "-11f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 2M",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "4f",
    "RECOVERY": "26f",
    "ADVANTAGE": "-11f",
    "GUARD": "LOW",
    "DAMAGE": 750,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 2S",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "3f",
    "RECOVERY": "49f",
    "ADVANTAGE": "-28f",
    "GUARD": "All",
    "DAMAGE": 800,
    "PRORATION init/comb": "70% / +2",
    "SPECIAL": "Charges 22S",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 2S (charged)",
    "FIRST ACTIVE": "17f, 34f",
    "ACTIVE": "",
    "RECOVERY": "Total frames 63f",
    "ADVANTAGE": "point blank: 6f",
    "GUARD": "All",
    "DAMAGE": "1440 raw, 180 scaled",
    "PRORATION init/comb": "80% +1 / +1 +1",
    "SPECIAL": "Consumes charge, Causes SKD",
    "EXTENSION": "",
    "": "80% +1 / +2 +1",
    "__1": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 5S",
    "FIRST ACTIVE": "1f; (19f  box enlargens)",
    "ACTIVE": "51f (33f large)",
    "RECOVERY": "13f",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "Gains 0,25 bar per hit, barrier extended as long as true string, succesful absorb negates recovery",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 5SS",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "4f",
    "RECOVERY": "30f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": 1000,
    "PRORATION init/comb": "60% / +2",
    "SPECIAL": "Invulnerable",
    "EXTENSION": "INITIAL SMASH",
    "": "(loses to grab, supers)",
    "__1": "1.15-1.17 70% / +2"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 5H",
    "FIRST ACTIVE": "1f; (8f  box enlargens)",
    "ACTIVE": "32f (24f large)",
    "RECOVERY": "13f",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "Gains 0,25 bar per hit, barrier extended as long as true string, succesful absorb negates recovery",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 5HS",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "4f",
    "RECOVERY": "30f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": 1000,
    "PRORATION init/comb": "60% / +2",
    "SPECIAL": "Invulnerable",
    "EXTENSION": "INITIAL SMASH",
    "": "(loses to grab, supers)",
    "__1": "1.15-1.17 70% / +2"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 6S",
    "FIRST ACTIVE": "Airborne at 12f",
    "ACTIVE": "Cancel from wall hop 7f",
    "RECOVERY": "Landing 7f",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "Stealth buffed from landing 9f > 7f",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
  {
    "MOVE": "> 4S",
    "FIRST ACTIVE": "Airborne at 12f",
    "ACTIVE": "Cancel from wall hop 7f",
    "RECOVERY": "Landing 7f",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "Stealth buffed from landing 9f > 7f",
    "EXTENSION": "",
    "": "",
    "__1": ""
  },
],
    supers: [
    ],
    assists: [

    ],

    combos: {

    },
  }
)
android18 = Character.create!(
  character: {
    bio: {
      name: 'android18',
      pictures: [],
      tier: 'A'
    },
    moves: [
  {
    "MOVE": "5L",
    "FIRST ACTIVE": "6f",
    "ACTIVE": "3f",
    "RECOVERY": "13f",
    "ADVANTAGE": "-4f",
    "GUARD": "LOW",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LL",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "4f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-4f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LLL",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "5f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": 1000,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "SMASH"
  },
  {
    "MOVE": "2L",
    "FIRST ACTIVE": "7f",
    "ACTIVE": "2f",
    "RECOVERY": "14f",
    "ADVANTAGE": "-4f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5M",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "4f",
    "RECOVERY": "18f",
    "ADVANTAGE": "-6f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "2M",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "6f",
    "RECOVERY": "18f",
    "ADVANTAGE": "-8f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5H",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "4f",
    "RECOVERY": "22f",
    "ADVANTAGE": "-10f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "2H",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "3f",
    "RECOVERY": "30f",
    "ADVANTAGE": "-17f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "Air invuln 4f - 15f",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "5S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "29f from first active",
    "ADVANTAGE": "-3f *",
    "GUARD": "All",
    "DAMAGE": 300,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "Chain up to 5",
    "EXTENSION": ""
  },
  {
    "MOVE": "2S",
    "FIRST ACTIVE": "32f",
    "ACTIVE": "6f",
    "RECOVERY": "13f + landing rec",
    "ADVANTAGE": "Blockstun: 21f *",
    "GUARD": "All",
    "DAMAGE": 600,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.L",
    "FIRST ACTIVE": "7f",
    "ACTIVE": "3f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.M",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "3f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.H",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "4f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.2H",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "8f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "j.S",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "-",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": 600,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "MOVE",
    "FIRST ACTIVE": "FIRST ACTIVE",
    "ACTIVE": "ACTIVE",
    "RECOVERY": "RECOVERY",
    "ADVANTAGE": "ADVANTAGE",
    "GUARD": "GUARD",
    "DAMAGE": "DAMAGE",
    "PRORATION init/comb": "PRORATION init/comb",
    "SPECIAL": "SPECIAL",
    "EXTENSION": "EXTENSION"
  },
  {
    "MOVE": "236L",
    "FIRST ACTIVE": "17f",
    "ACTIVE": "1f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": "600 + raw:800/cmb:1000",
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": "Causes SKD"
  },
  {
    "MOVE": "236M",
    "FIRST ACTIVE": "30f",
    "ACTIVE": "1f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": "600, 1100",
    "PRORATION init/comb": "80% +1 / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "236[M]",
    "FIRST ACTIVE": "30f",
    "ACTIVE": "1f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 600,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "236H",
    "FIRST ACTIVE": "28f",
    "ACTIVE": "1f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": "700, 1100",
    "PRORATION init/comb": "80% +1 / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "236[H]",
    "FIRST ACTIVE": "28f",
    "ACTIVE": "1f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214L",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "8f",
    "RECOVERY": "Anim total 39f, A17: 66f",
    "ADVANTAGE": "Blockstun: 21f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "Summon appears at 7f",
    "EXTENSION": ""
  },
  {
    "MOVE": "214M",
    "FIRST ACTIVE": "32f ; 49f [+ on hit 68f]",
    "ACTIVE": "4f ; 4f ; X",
    "RECOVERY": "Anim total 39f, A17: 59f",
    "ADVANTAGE": "Blockstun: 35f",
    "GUARD": "All",
    "DAMAGE": "400, 400, 400",
    "PRORATION init/comb": "80% +1 +1 / +1 +1 +1",
    "SPECIAL": "Summon appears at 7f",
    "EXTENSION": ""
  },
  {
    "MOVE": "214H",
    "FIRST ACTIVE": "13f [41f when triggered]",
    "ACTIVE": "300f [~40f triggered]",
    "RECOVERY": "Anim total 32f, A17: 20f",
    "ADVANTAGE": "Blockstun: 51f",
    "GUARD": "All",
    "DAMAGE": "Total: 1717",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "Summon appears at 13f",
    "EXTENSION": ""
  },
  {
    "MOVE": "214S",
    "FIRST ACTIVE": "43f ; 52f ; 61f",
    "ACTIVE": "-",
    "RECOVERY": "Anim total 39f, A17: 77f",
    "ADVANTAGE": "Blockstun chain: 38f *",
    "GUARD": "All",
    "DAMAGE": 300,
    "PRORATION init/comb": "80% +1 +1 / +1 +1 +1",
    "SPECIAL": "Summon appears at 15f",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214L",
    "FIRST ACTIVE": "20f",
    "ACTIVE": "3f",
    "RECOVERY": "Anim total 39f, A17: 84f",
    "ADVANTAGE": "Blockstun: 21f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "Summon appears at 7f",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214M",
    "FIRST ACTIVE": "33f ; 52f",
    "ACTIVE": "4f ; 4f",
    "RECOVERY": "Anim total 32f, A17: 58f",
    "ADVANTAGE": "Blockstun: 47f",
    "GUARD": "All",
    "DAMAGE": "450, 450",
    "PRORATION init/comb": "80% +1 / +1 +1",
    "SPECIAL": "7f uncancellable landing lag, Summon appears at 13f",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214H",
    "FIRST ACTIVE": "13f [41f when triggered]",
    "ACTIVE": "300f [~40f triggered]",
    "RECOVERY": "Anim total 32f, A17: 20f",
    "ADVANTAGE": "Blockstun: 51f",
    "GUARD": "All",
    "DAMAGE": "Total: 1717",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "Summon appears at 13f",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214S",
    "FIRST ACTIVE": "26f",
    "ACTIVE": "40f",
    "RECOVERY": "Anim total 32f, A17: 73f",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "-",
    "PRORATION init/comb": "Gain 0,25bar per absorbed hit, Summon appears at 13f",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "20f",
    "ACTIVE": "-",
    "RECOVERY": "30f from first active",
    "ADVANTAGE": "point blank: -3f",
    "GUARD": "All",
    "DAMAGE": 1000,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "Causes massive chip, Can be angled with 2/8",
    "EXTENSION": ""
  },
  {
    "MOVE": "22S",
    "FIRST ACTIVE": "4f",
    "ACTIVE": "36f",
    "RECOVERY": "9f",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "-",
    "PRORATION init/comb": "Gain 0,25bar per absorbed hit",
    "SPECIAL": "",
    "EXTENSION": "Super cancellable"
  },
  {
    "MOVE": "j.22S",
    "FIRST ACTIVE": "4f",
    "ACTIVE": "36f",
    "RECOVERY": "9f",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "-",
    "PRORATION init/comb": "Gain 0,25bar per absorbed hit",
    "SPECIAL": "",
    "EXTENSION": "Super cancellable"
  },
],
    supers: [
    ],
    assists: [

    ],

    combos: {

    },
  }
)
android21 = Character.create!(
  character: {
    bio: {
      name: 'character',
      pictures: [],
      tier: 'A'
    },
    moves: [
  {
    "MOVE": "5L",
    "FIRST ACTIVE": "6f",
    "ACTIVE": "3f",
    "RECOVERY": "12f",
    "ADVANTAGE": "-3f",
    "GUARD": "All",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LL",
    "FIRST ACTIVE": "9f",
    "ACTIVE": "4f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-4f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LLL",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "4f",
    "RECOVERY": "17f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": 1000,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "SMASH"
  },
  {
    "MOVE": "2L",
    "FIRST ACTIVE": "7f",
    "ACTIVE": "2f",
    "RECOVERY": "12f",
    "ADVANTAGE": "-2f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5M",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "4f",
    "RECOVERY": "18f",
    "ADVANTAGE": "-6f ~ -4f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "1f - 2f short, 3f - 4f long",
    "EXTENSION": ""
  },
  {
    "MOVE": "2M",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "no hitbox displayed",
    "RECOVERY": "",
    "ADVANTAGE": "-10f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "3M",
    "FIRST ACTIVE": "17f",
    "ACTIVE": "no hitbox displayed",
    "RECOVERY": "",
    "ADVANTAGE": "-10f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5H",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "4f",
    "RECOVERY": "20f",
    "ADVANTAGE": "-8f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "2H",
    "FIRST ACTIVE": "16f",
    "ACTIVE": "3f",
    "RECOVERY": "32f",
    "ADVANTAGE": "-19f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "5S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "24f from first active",
    "ADVANTAGE": "-4f *",
    "GUARD": "All",
    "DAMAGE": 600,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "3 hits, counts as one",
    "EXTENSION": ""
  },
  {
    "MOVE": "2S",
    "FIRST ACTIVE": "21f",
    "ACTIVE": "-",
    "RECOVERY": "25f from first acitve",
    "ADVANTAGE": "Point blank: 6f *",
    "GUARD": "All",
    "DAMAGE": "450 x3",
    "PRORATION init/comb": "80% / +1 +1 +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.L",
    "FIRST ACTIVE": "6f",
    "ACTIVE": "3f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.M",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "4f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.H",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "5f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.2H",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "4f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "j.S",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "-",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "400 x3",
    "PRORATION init/comb": "80% / +1 +1 +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "MOVE",
    "FIRST ACTIVE": "FIRST ACTIVE",
    "ACTIVE": "ACTIVE",
    "RECOVERY": "RECOVERY",
    "ADVANTAGE": "ADVANTAGE",
    "GUARD": "GUARD",
    "DAMAGE": "DAMAGE",
    "PRORATION init/comb": "PRORATION init/comb",
    "SPECIAL": "SPECIAL",
    "EXTENSION": "EXTENSION"
  },
  {
    "MOVE": "236L",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "-",
    "RECOVERY": "38f from first active",
    "ADVANTAGE": "-10f point blank",
    "GUARD": "All",
    "DAMAGE": 900,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236M",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "-",
    "RECOVERY": "32f from first active",
    "ADVANTAGE": "-4f point blank",
    "GUARD": "All",
    "DAMAGE": 900,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236H (1bar) lv.0",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "38f from first active",
    "ADVANTAGE": "-2f",
    "GUARD": "All",
    "DAMAGE": 900,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236H (1bar) lv.1",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "26f from first active",
    "ADVANTAGE": "4f",
    "GUARD": "All",
    "DAMAGE": "700, 700",
    "PRORATION init/comb": "80% / +1 +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236H (1bar) lv.2",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "26f from first active",
    "ADVANTAGE": "9f",
    "GUARD": "All",
    "DAMAGE": "700, 700, 700",
    "PRORATION init/comb": "80% +1 +1 / +1 n3",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236H (1bar) lv.3",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "26f from first active",
    "ADVANTAGE": "14f",
    "GUARD": "All",
    "DAMAGE": "700, 700, 700, 700",
    "PRORATION init/comb": "80% +1 n3 / +1 n4",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236H (1bar) lv.4",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "26f from first active",
    "ADVANTAGE": "19f",
    "GUARD": "All",
    "DAMAGE": "700, 700, 700, 700, 700",
    "PRORATION init/comb": "80% +1 n4 / +1 n5",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214L",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "until lands / 3f landing",
    "RECOVERY": "22f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": "0, 1000 [ 200, 300 ]",
    "PRORATION init/comb": "90% +1 / +2 (2nd hit scales)",
    "SPECIAL": "1f - 2f initial hitbox large, dive reduces to head size hitbox, [value after smash]",
    "EXTENSION": ""
  },
  {
    "MOVE": "214M",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "until lands / 3f landing",
    "RECOVERY": "22f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": "0, 1100 [ 200, 300 ]",
    "PRORATION init/comb": "90% +1 / +2 (2nd hit scales)",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "214H (1bar)",
    "FIRST ACTIVE": "14f",
    "ACTIVE": "until lands / 3f landing",
    "RECOVERY": "22f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": "0, 1200 [ 600, 1000 ]",
    "PRORATION init/comb": "90% +1 / +2 (2nd hit scales)",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH, Bounce"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214L",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "until lands / 3f landing",
    "RECOVERY": "22f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": "0, 1000 [ 200, 300 ]",
    "PRORATION init/comb": "90% +1 / +2 (2nd hit scales)",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "j.214M",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "until lands / 3f landing",
    "RECOVERY": "22f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": "0, 1100 [ 200, 300 ]",
    "PRORATION init/comb": "90% +1 / +2 (2nd hit scales)",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH, Wall"
  },
  {
    "MOVE": "j.214H (1bar)",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "until lands / 3f landing",
    "RECOVERY": "22f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": "0, 1200 [ 600, 1000 ]",
    "PRORATION init/comb": "90% +1 / +2 (2nd hit scales)",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH, Bounce"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "27f",
    "ACTIVE": "1f",
    "RECOVERY": "17f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 900,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "Second hit doesn't scale",
    "EXTENSION": "214X cancellable"
  },
  {
    "MOVE": "214S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "9f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 900,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "Anti air at 4f - 13f",
    "EXTENSION": "214X cancellable"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "3f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 900,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": "214X cancellable"
  },
  {
    "MOVE": "j.214S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "9f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 900,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "",
    "EXTENSION": "214X cancellable"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "12f, last 48f",
    "ACTIVE": "-",
    "RECOVERY": "38f from last projectile",
    "ADVANTAGE": "Ground -13f *, Air -7f*",
    "GUARD": "All",
    "DAMAGE": "170 x8",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "First hit scales",
    "EXTENSION": ""
  },
  {
    "MOVE": "214S",
    "FIRST ACTIVE": "17f",
    "ACTIVE": "5f",
    "RECOVERY": "12f",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1400,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "Air invuln 1f - 21f",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236S",
    "FIRST ACTIVE": "12f, last 48f",
    "ACTIVE": "-",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "170 x8",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "First hit scales",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214S",
    "FIRST ACTIVE": "16f",
    "ACTIVE": "5f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "Throw",
    "DAMAGE": 1400,
    "PRORATION init/comb": "70% / +1",
    "SPECIAL": "Air invuln 1f - 20f",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "19f",
    "ACTIVE": "Until lands, blast 5f",
    "RECOVERY": "24f from first active",
    "ADVANTAGE": "~ 11f*",
    "GUARD": "All",
    "DAMAGE": "500, 500, 700, 700",
    "PRORATION init/comb": "90% +1n3 / +1 n4",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214S",
    "FIRST ACTIVE": "invuln at 4f",
    "ACTIVE": "4f - 41f",
    "RECOVERY": "9f",
    "ADVANTAGE": "-",
    "GUARD": "Strikes & Projectiles",
    "DAMAGE": "-",
    "PRORATION init/comb": "-",
    "SPECIAL": "0,25 bar gain on absorb",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236S",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "Until lands, blast 5f",
    "RECOVERY": "-",
    "ADVANTAGE": "~ 8f*",
    "GUARD": "All",
    "DAMAGE": "500, 500, 700, 700",
    "PRORATION init/comb": "90% +1n3 / +1 n4",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214S",
    "FIRST ACTIVE": "invuln at 4f",
    "ACTIVE": "4f - 41f",
    "RECOVERY": "9f",
    "ADVANTAGE": "-",
    "GUARD": "Strikes & Projectiles",
    "DAMAGE": "-",
    "PRORATION init/comb": "-",
    "SPECIAL": "0,25 bar gain on absorb",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "25f",
    "RECOVERY": "25f",
    "ADVANTAGE": "-8f point blank",
    "GUARD": "All",
    "DAMAGE": "262 x5",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214S",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "5f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-1f",
    "GUARD": "All",
    "DAMAGE": 0,
    "PRORATION init/comb": "90% / +0",
    "SPECIAL": "air invuln 4f - 10f",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236S",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "25f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "262 x5",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214S",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "5f",
    "RECOVERY": "-",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": 0,
    "PRORATION init/comb": "90% / +0",
    "SPECIAL": "air invuln 4f - 10f",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "{300f}",
    "RECOVERY": "27f from first active",
    "ADVANTAGE": "Blockstun 25f *",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214S",
    "FIRST ACTIVE": "invuln at 15f",
    "ACTIVE": "15f - 26f",
    "RECOVERY": "6f after invuln",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "-",
    "PRORATION init/comb": "-",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236S",
    "FIRST ACTIVE": "18f",
    "ACTIVE": "{300f}",
    "RECOVERY": "-",
    "ADVANTAGE": "Blockstun 25f *",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214S",
    "FIRST ACTIVE": "invuln at 15f",
    "ACTIVE": "15f - 26f",
    "RECOVERY": "11f after invuln",
    "ADVANTAGE": "-",
    "GUARD": "-",
    "DAMAGE": "-",
    "PRORATION init/comb": "-",
    "SPECIAL": "",
    "EXTENSION": ""
  },
],
    supers: [
    ],
    assists: [

    ],

    combos: {

    },
  }
)
bardock = Character.create!(
  character: {
    bio: {
      name: 'Bardock',
      pictures: [],
      tier: 'S'
    },
    moves: [
  {
    "MOVE": "5L",
    "FIRST ACTIVE": "6f",
    "ACTIVE": "3f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-3f",
    "GUARD": "All",
    "DAMAGE": 400,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LL",
    "FIRST ACTIVE": "11f",
    "ACTIVE": "3f",
    "RECOVERY": "18f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "1f - 2f hitbox reaches high",
    "EXTENSION": ""
  },
  {
    "MOVE": "5LLL",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "3f",
    "RECOVERY": "17f",
    "ADVANTAGE": "-4f",
    "GUARD": "All",
    "DAMAGE": 1000,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "SMASH"
  },
  {
    "MOVE": "2L",
    "FIRST ACTIVE": "7f",
    "ACTIVE": "3f",
    "RECOVERY": "13f",
    "ADVANTAGE": "-4f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5M",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "4f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-4f",
    "GUARD": "All",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "2M",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "3f",
    "RECOVERY": "18f",
    "ADVANTAGE": "-5f",
    "GUARD": "LOW",
    "DAMAGE": 700,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "5H",
    "FIRST ACTIVE": "15f",
    "ACTIVE": "3f",
    "RECOVERY": "21f",
    "ADVANTAGE": "-8f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "2H",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "3f",
    "RECOVERY": "28f",
    "ADVANTAGE": "-15f",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "Air invuln 4f - 15f",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "5S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "25f from first active",
    "ADVANTAGE": "PB: -4f * Blockstun: 21f",
    "GUARD": "All",
    "DAMAGE": 500,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.L",
    "FIRST ACTIVE": "6f",
    "ACTIVE": "3f",
    "RECOVERY": "13f",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": "500, 500",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.M",
    "FIRST ACTIVE": "8f ; 19f",
    "ACTIVE": "2f ; 2f",
    "RECOVERY": "13f",
    "ADVANTAGE": "-",
    "GUARD": "HIGH ; HIGH",
    "DAMAGE": 700,
    "PRORATION init/comb": "80% +1 / +1 +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.H",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "4f",
    "RECOVERY": "19f",
    "ADVANTAGE": "-",
    "GUARD": "HIGH",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.2H",
    "FIRST ACTIVE": "12f",
    "ACTIVE": "4f",
    "RECOVERY": "22f",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": 850,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "j.S",
    "FIRST ACTIVE": "13f",
    "ACTIVE": "-",
    "RECOVERY": "22f from first active, 5f landing recovery // Adv: -",
    "ADVANTAGE": "",
    "GUARD": "All",
    "DAMAGE": 500,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "MOVE",
    "FIRST ACTIVE": "FIRST ACTIVE",
    "ACTIVE": "ACTIVE",
    "RECOVERY": "RECOVERY",
    "ADVANTAGE": "ADVANTAGE",
    "GUARD": "GUARD",
    "DAMAGE": "DAMAGE",
    "PRORATION init/comb": "PRORATION init/comb",
    "SPECIAL": "SPECIAL",
    "EXTENSION": "EXTENSION"
  },
  {
    "MOVE": "236L",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "7f",
    "RECOVERY": "20f",
    "ADVANTAGE": "-5f (Forced)",
    "GUARD": "All",
    "DAMAGE": 900,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236M",
    "FIRST ACTIVE": "8f ; 17f",
    "ACTIVE": "6f ; 5f",
    "RECOVERY": "21f (Airborne), 5f landing rec // Adv: -16f",
    "ADVANTAGE": "",
    "GUARD": "All",
    "DAMAGE": "300, 600 [1100 2nd hit only]",
    "PRORATION init/comb": "80% +1 / +1 +1",
    "SPECIAL": "Air invuln 4f - 21f",
    "EXTENSION": "INITIAL SMASH"
  },
  {
    "MOVE": "236H",
    "FIRST ACTIVE": "8f",
    "ACTIVE": "3f~7f ; 3f ; 5f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-5f (Forced)",
    "GUARD": "All",
    "DAMAGE": "300, 600 / 300, 1100",
    "PRORATION init/comb": "70% +2 / +2 +2 far: 80% / +1",
    "SPECIAL": "Attack has 3f minimun proximity period, if it connects the third attack will cancel out, resulting in less dmg",
    "EXTENSION": ""
  },
  {
    "MOVE": "236H > X",
    "FIRST ACTIVE": "Combo only, useless data",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "300, 750",
    "PRORATION init/comb": "- / +1 +1",
    "SPECIAL": "",
    "EXTENSION": "Juggle"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236L",
    "FIRST ACTIVE": "10f",
    "ACTIVE": "7f",
    "RECOVERY": "17f",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": 900,
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236M",
    "FIRST ACTIVE": "12f (2f gap before landing)",
    "ACTIVE": "Until lands ; 3f",
    "RECOVERY": "28f",
    "ADVANTAGE": "-5f",
    "GUARD": "All",
    "DAMAGE": "300, 600 [1100 2nd hit only]",
    "PRORATION init/comb": "80% +1 / +1 +1",
    "SPECIAL": "",
    "EXTENSION": "Bounce"
  },
  {
    "MOVE": "j.236H",
    "FIRST ACTIVE": "8f",
    "ACTIVE": "3f~7f ; 3f ; 5f",
    "RECOVERY": "24f",
    "ADVANTAGE": "-",
    "GUARD": "All",
    "DAMAGE": "300, 600 / 300, 1100",
    "PRORATION init/comb": "70% +2 / +2 +2 far: 80% / +1",
    "SPECIAL": "Attack has 3f minimun proximity period, if it connects the third attack will cancel out, resulting in less dmg",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.236H > X",
    "FIRST ACTIVE": "Combo only, useless data",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "300, 750",
    "PRORATION init/comb": "- / +1 +1",
    "SPECIAL": "",
    "EXTENSION": "Juggle"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "214L",
    "FIRST ACTIVE": "10f ; 24f",
    "ACTIVE": "10f ; 5f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-5f",
    "GUARD": "All ; HIGH",
    "DAMAGE": "50, 40 x3 + 1000",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "SKD"
  },
  {
    "MOVE": "214M",
    "FIRST ACTIVE": "8f ; 27f",
    "ACTIVE": "15f ; 5f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-5f",
    "GUARD": "All ; HIGH",
    "DAMAGE": "50, 40 x5 + 1100",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "Bounce, SKD"
  },
  {
    "MOVE": "214H",
    "FIRST ACTIVE": "7f ; 22f",
    "ACTIVE": "14f ; 5f",
    "RECOVERY": "16f",
    "ADVANTAGE": "-5f",
    "GUARD": "All ; HIGH",
    "DAMAGE": "50, 40 x5 + 1300",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "Bounce, SKD"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "j.214L",
    "FIRST ACTIVE": "11f ; 23f",
    "ACTIVE": "8f ; 5f",
    "RECOVERY": "15f",
    "ADVANTAGE": "-",
    "GUARD": "All ; HIGH",
    "DAMAGE": "50, 40 x3 + 800",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "SKD"
  },
  {
    "MOVE": "j.214M",
    "FIRST ACTIVE": "19f ;",
    "ACTIVE": "13f ;",
    "RECOVERY": "21f",
    "ADVANTAGE": "-",
    "GUARD": "All ; HIGH",
    "DAMAGE": "50, 40 x5 + 1000",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "Bounce, SKD"
  },
  {
    "MOVE": "j.214H",
    "FIRST ACTIVE": "8f ; 22f",
    "ACTIVE": "13f ;",
    "RECOVERY": "15f",
    "ADVANTAGE": "-",
    "GUARD": "All ; HIGH",
    "DAMAGE": "50, 40 x5 + 1200",
    "PRORATION init/comb": "80% / +1",
    "SPECIAL": "",
    "EXTENSION": "Bounce, SKD"
  },
  {
    "MOVE": "",
    "FIRST ACTIVE": "",
    "ACTIVE": "",
    "RECOVERY": "",
    "ADVANTAGE": "",
    "GUARD": "",
    "DAMAGE": "",
    "PRORATION init/comb": "",
    "SPECIAL": "",
    "EXTENSION": ""
  },
  {
    "MOVE": "236S",
    "FIRST ACTIVE": "26f [hold 27f - 48f]",
    "ACTIVE": "2f",
    "RECOVERY": "21f",
    "ADVANTAGE": "4f",
    "GUARD": "All",
    "DAMAGE": "600, 600 [800, 800]",
    "PRORATION init/comb": "90% / +1",
    "SPECIAL": "Extra damage 38f - 48f",
    "EXTENSION": "Wall Splat"
  },

],
    supers: [
    ],
    assists: [

    ],

    combos: {

    },
  }
)



puts 'success'




# character frame data
# https://docs.google.com/spreadsheets/d/1-p29UmRGIPF6n17ddOEtYfLcn_KRlE2VH6tE61P5UM8/edit

# assist fram data
# https://docs.google.com/spreadsheets/d/1IIpmO2wDU2KZV7tYQhcK3hB0Z_Mg1H18HFeDox9LZ9o/edit#gid=0
